# /// script
# requires-python = ">=3.11"
# ///
"""Generate `src/mspm0_parts/table.rs` from the mspm0-data catalog.

The pin-to-PINCM mapping is per part and is not an arithmetic function of the pin. It equals
`pin + 1` on 14 of the 43 parts and on the other 29 the difference ranges from -27 to +78, so a
table is the only correct answer. A second port continues the same PINCM numbering rather than
restarting, which is why the key here is (port, pin) and not a per-port index.

Writes only the table. The functions over it are hand-written in `src/mspm0_parts/mod.rs`, so
this must not be pointed at that file.

Usage:  uv run tools/generate_iomux.py <DATA_DIR> > src/mspm0_parts/table.rs

        DATA_DIR is the `data/` directory of the mspm0-data catalog, or set MSPM0_DATA_DIR:
        https://github.com/CordlessCoder/mspm0-data-generated
"""

import json
import os
import pathlib
import re
import sys

if len(sys.argv) > 1:
    data = pathlib.Path(sys.argv[1])
elif "MSPM0_DATA_DIR" in os.environ:
    data = pathlib.Path(os.environ["MSPM0_DATA_DIR"])
else:
    sys.exit(__doc__.strip())

parts = []
for path in sorted(data.glob("*.json")):
    chip = json.load(path.open())
    pins = []
    for name, pincm in chip["iomux"].items():
        m = re.fullmatch(r"P([A-Z])(\d+)", name)
        if not m:
            continue
        port = ord(m.group(1)) - ord("A")
        pins.append((port, int(m.group(2)), pincm))
    if pins:
        parts.append((chip["name"].lower(), sorted(pins)))

out = sys.stdout.write
out("""//! The pin-to-`PINCM` table, one entry per part.
//!
//! **Generated by `tools/generate_iomux.py` from the mspm0-data catalog. Do not edit.**
//! The reasoning for why this is a table lives in the parent module, which is hand-written.

/// `(port, pin, pincm)`, sorted, where port 0 is `PA`.
pub type Pins = &'static [(u8, u8, u8)];

""")

out(f"/// Every part in the catalog, by lowercased name.\npub static PARTS: [(&str, Pins); {len(parts)}] = [\n")
for name, pins in parts:
    body = ", ".join(f"({p},{n},{c})" for p, n, c in pins)
    out(f'    ("{name}", &[{body}]),\n')
out("];\n")
