# /// script
# requires-python = ">=3.11"
# ///
"""Generate `src/mspm0_parts/flash.rs` from the mspm0-data catalog.

The flash controller's command sequence is the same on every part. What differs is how many
sectors each write-protection register covers, whether the flash carries ECC, and two facts about
the SYSCTL block: whether it has `SHUTDNSTORE`, and whether its banks can run swapped. The HAL
takes the same facts from the same catalog at build time; this is the host's copy of them.

Writes only the table. The code over it is hand-written in `src/mspm0_flashctl.rs`.

Usage:  uv run tools/generate_flash.py <DATA_DIR> > src/mspm0_parts/flash.rs

        DATA_DIR is the `data/` directory of the mspm0-data catalog, or set MSPM0_DATA_DIR:
        https://github.com/CordlessCoder/mspm0-data-generated
"""

import io
import json
import os
import pathlib
import subprocess
import sys

if len(sys.argv) > 1:
    data = pathlib.Path(sys.argv[1])
elif "MSPM0_DATA_DIR" in os.environ:
    data = pathlib.Path(os.environ["MSPM0_DATA_DIR"])
else:
    sys.exit(__doc__.strip())

# Per SYSCTL register block, as the HAL's build script keys them: (SHUTDNSTORE, FLBANKSWP).
# An unknown block is an error, because a new one has to be looked at.
SYSCTL = {
    "c110x": (True, False),
    "c1105_c1106": (True, False),
    "l110x_l130x_l134x": (True, False),
    "l122x_l222x": (True, True),
    "h321x": (False, False),
    "g350x_g310x_g150x_g110x": (True, False),
    "g351x_g151x": (True, True),
    "g518x": (True, True),
}

rows = []
for path in sorted(data.glob("*.json")):
    chip = json.load(path.open())
    peripherals = chip["peripherals"]
    flashctl = peripherals.get("FLASHCTL", {}).get("flashctl")
    if flashctl is None:
        continue
    version = peripherals["SYSCTL"]["version"]
    if version not in SYSCTL:
        sys.exit(f"{chip['name']}: unknown SYSCTL block {version!r}")
    if flashctl["sector_bytes"] != 1024:
        sys.exit(f"{chip['name']}: a {flashctl['sector_bytes']}-byte sector")
    # The G518x states 16, which is its widest multi-word program; its flash word is still 64 bits.
    if flashctl["word_bytes"] not in (8, 16):
        sys.exit(f"{chip['name']}: a {flashctl['word_bytes']}-byte flash word")
    if flashctl["weprotc_bits"] != 0:
        sys.exit(f"{chip['name']}: CMDWEPROTC, which the unprotect step does not reach")
    shutdnstore, bank_swap = SYSCTL[version]
    rows.append((chip["name"].lower(), flashctl, shutdnstore, bank_swap))

_buffer = io.StringIO()
out = _buffer.write
out("""//! Each part's flash controller geometry.
//!
//! **Generated by `tools/generate_flash.py` from the mspm0-data catalog. Do not edit.**

use crate::mspm0_flashctl::Geometry;

/// Every part in the catalog with a flash controller, by lowercased name.
""")
out(f"pub static FLASH: [(&str, Geometry); {len(rows)}] = [\n")
for name, f, shutdnstore, bank_swap in rows:
    out(
        f'    ("{name}", Geometry {{ weprota_bits: {f["weprota_bits"]}, weprotb_bits: {f["weprotb_bits"]}, '
        f'has_ecc: {str(f["has_ecc"]).lower()}, shutdnstore: {str(shutdnstore).lower()}, '
        f"bank_swap: {str(bank_swap).lower()} }}),\n"
    )
out("];\n")

formatted = subprocess.run(
    ["rustfmt", "--edition", "2024", "--config", "max_width=120", "--emit", "stdout"],
    input=_buffer.getvalue(),
    capture_output=True,
    text=True,
    check=True,
).stdout
sys.stdout.write(formatted.split("\n", 2)[2] if formatted.startswith("stdin:") else formatted)
